.github/workflows/code_health.yaml

Fix the error: Couldn't find a release tarball containing binaries for latest. 
See: https://github.com/est31/cargo-udeps/issues/157

ci: fix workflow for detecting unused dependencies

---

.github/workflows/pr_title.yaml

This workflows makes sure that PR titles conform https://www.conventionalcommits.org/en/v1.0.0/

ci: fix workflow that checks PR titles

---

docs/Module Developer's Guide.md
yara-x-macros/src/module_main.rs
yara-x/build.rs
yara-x/src/lib.rs
yara-x/src/modules/elf/mod.rs
yara-x/src/modules/hash/mod.rs
yara-x/src/modules/lnk/mod.rs
yara-x/src/modules/macho/mod.rs
yara-x/src/modules/mod.rs
yara-x/src/modules/modules.rs
yara-x/src/modules/string.rs
yara-x/src/modules/test_proto2/mod.rs
yara-x/src/modules/test_proto3/mod.rs
yara-x/src/modules/tests.rs
yara-x/src/modules/text.rs
yara-x/src/modules/time.rs
yara-x/src/scanner/mod.rs

With this new API you use a YARA module as a file-parsing tool, and obtain the results produced by the module without any YARA rule involved in the process. This is useful for external tools that what to leverage YARA's file parsing capabilities for their own purposes.
This required changing the arguments passed to the main function of each module, from `&ScanContext` to `&[u8]`.

feat: implement new API that allows invoking YARA modules directly

---

yara-x-macros/src/module_export.rs
yara-x-macros/src/wasm_export.rs
yara-x-parser/src/ast/ascii_tree.rs
yara-x-parser/src/ast/mod.rs
yara-x-parser/src/parser/cst2ast.rs
yara-x-parser/src/parser/tests/testdata/general.yaml
yara-x/src/compiler/context.rs
yara-x/src/compiler/emit.rs
yara-x/src/compiler/ir/ast2ir.rs
yara-x/src/compiler/ir/mod.rs
yara-x/src/compiler/mod.rs
yara-x/src/modules/test_proto2/tests/mod.rs
yara-x/src/modules/tests.rs
yara-x/src/scanner/context.rs
yara-x/src/scanner/mod.rs
yara-x/src/string_pool.rs
yara-x/src/symbols/mod.rs
yara-x/src/types/array.rs
yara-x/src/types/func.rs
yara-x/src/types/mod.rs
yara-x/src/types/structure.rs
yara-x/src/variables.rs
yara-x/src/wasm/mod.rs
yara-x/src/wasm/string.rs

This refactor started as an attempt to fix a bug in the logic for structure field lookups, but fixing this issue required more fundamental changes. Some of the changes are:
* TypeValue::String now has a reference-counted string
* WasmArg has been refactored for making Rust-to-WASM type conversions simpler
* ScanContext now contains a map of used objects (structs, arrays, maps or strings) for tracking values that are passed from Rust to WASM and back to Rust.
* The field lookup mechanism for finding fields a structure has been refactored.

refactor: big refactor that addresses multiple issues

---

yara-x-macros/src/lib.rs
yara-x-macros/src/module_export.rs
yara-x-macros/src/wasm_export.rs
yara-x/src/compiler/context.rs
yara-x/src/compiler/emit.rs
yara-x/src/compiler/ir/ast2ir.rs
yara-x/src/compiler/ir/mod.rs
yara-x/src/compiler/mod.rs
yara-x/src/modules/protos/test_proto2.proto
yara-x/src/modules/test_proto2/mod.rs
yara-x/src/modules/test_proto2/tests/mod.rs
yara-x/src/scanner/context.rs
yara-x/src/symbols/mod.rs
yara-x/src/types/array.rs
yara-x/src/types/func.rs
yara-x/src/types/map.rs
yara-x/src/types/mod.rs
yara-x/src/types/structure.rs
yara-x/src/wasm/builder.rs
yara-x/src/wasm/mod.rs

A mechanism for supporting method calls is now implemented. Only structs can have methods at this time, but in the future this can be extended to other types like maps and arrays.
The `module_export` and `wasm_export` now have a new argument `method_of` that allows to specify that a WASM-exported function is a method of some type. For example:
```
#[module_export(method_of = "test_proto2.NestedProto2")]
fn some_function(ctx: &mut ScanContext, structure: Rc<Struct>) {
... // here the `structure` argument is a `NestedProto2`
}
```

feat: implement method calls

---

yara-x/src/modules/dotnet/parser.rs
yara-x/src/modules/dotnet/tests/testdata/88d0d0692e675cd5fafb57db4f940e98d03e054ca2b88ef5a41f72b5787841b3.out
yara-x/src/modules/dotnet/tests/testdata/984750efd1cb94e5ca7b366863af2092af954dad65df534bff603b9afcb49cd4.out

Fix issues in `dotnet` module, specifically:
* Parsing of array dimensions was incorrect because low boundaries were parsed as unsigned variable-length integers, and they are *signed*.
* Generic arguments in classes and method were not properly handled.

fix: multiple issues in `dotnet` module

---

.github/workflows/code_health.yaml
.github/workflows/coverage.yaml
.github/workflows/python.yaml
.github/workflows/tests.yaml

I've cleaned up all of the following messages in the GitHub Actions workflows output:
> The following actions uses node12 which is deprecated and will be forced to run on node16: `<specific action>`. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[`actions-rs/cargo`](https://github.com/actions-rs/cargo) has been archived and is no longer maintained, plus we can run `cargo test` instead of relying on a GitHub Action to do so for us. 
The only one I could not clean up manually is the following:
> The following actions uses node12 which is deprecated and will be forced to run on node16: `aig787/cargo-udeps-action@v1`. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run- …

chore: Fix deprecated node12 warnings in actions workflows

---

yara-x/src/modules/macho/mod.rs
yara-x/src/modules/macho/tests/mod.rs
yara-x/src/modules/macho/tests/testdata/tiny_universal.out
yara-x/src/modules/modules.rs
yara-x/src/modules/protos/macho.proto
yara-x/src/wasm/builder.rs

- implemented LC_ID_DYLINKER, LC_LOAD_DYLINKER, and LC_DYLD_ENVIRONMENT load commands
- fixed bug in parsing for RPath and Dylibs where swap needed to occur before taking offset
- implemented search functions for rpath and dylibs with `macho.rpath_present` and `macho.dylib_present`

feat: mach-o load command parsing features + fix bug

---

docs/Module Developer's Guide.md

Noticed the intelhex format and how to generate the test data wasn't documented. It is now :smile_cat:

docs: add documentation for generating testdata input

---

yara-x/src/compiler/emit.rs
yara-x/src/compiler/errors.rs
yara-x/src/compiler/ir/ast2ir.rs
yara-x/src/compiler/ir/mod.rs
yara-x/src/compiler/tests/errors.rs

This keyword was deprecated in YARA since long ago.

feat: return error when the entrypoint keyword is used

---

.github/workflows/coverage.yaml
.github/workflows/tests.yaml

Similar problem to #66, except node16 is now deprecated.
Only action using node16 now is the `aig787/cargo-udeps-action` check:
I've created a PR to fix for the udeps action: https://github.com/aig787/cargo-udeps-action/pull/5

chore: Fix deprecated node16 warnings in actions workflows

---

lib/src/modules/macho/mod.rs
lib/src/modules/macho/parser.rs
lib/src/modules/macho/tests/mod.rs

Also implemented `build_version_command` in a more idiomatic way.

chore: rename macho module functions from x_present to has_x.

---

lib/src/compiler/rules.rs

fix: set a larger limit for NFA when compiling regular expressions

---

lib/src/compiler/emit.rs
lib/src/tests/mod.rs

fix: issue with `for .. in .. loop` returning undefined value instead

---

.github/workflows/release.yaml

When adding a tag `vX.Y.Z`, the release workflow makes sure that the crate version is `X.Y.Z`. The prevents creating tags that doesn't correspond to the version declared in Cargo.toml.

ci: check that tag numbers are in sync with crate version

---

lib/src/scanner/context.rs
lib/src/scanner/matches.rs
lib/src/scanner/mod.rs
lib/src/wasm/mod.rs

`ScanContext` contains hash maps that tracks the matches found for each pattern. The values in these maps are vectors that can become very large. For performance reasons, instead of completely deallocating those vectors after each scan, we were clearing the vector but retaining its capacity, so that they can be reused in later scans. The problem with that is that these vectors are not freed while the scanner is in use, and this can have a large impact on the process' memory footprint, causing OOM issues.
This PR adds a `PatternMatches` type that encapsulates all the logic for tracking pattern matches, including a more sophisticated approach that tries to reuse the vectors as much as possible, but frees them when they grow too much.

fix: out of memory issue due to accumulation of items in `ScanContext`

---

lib/src/modules/pe/authenticode.rs
lib/src/modules/pe/tests/testdata/130f9b2e65bfceae8d9e7cbe205471fc8ee34c3d9996f77baa3c3ab47a3b3068.out

The signature of the signed attributes was verified, the digest of countersigned signature was verified but what was missing is the verification that the signed attributes are actually signing the embedded timestamp information. This would allow anyone to take a valid countersignature, replace content info of the signed data with their own timestamp info, recalculate hash against the countersigned signature and it would be verified as OK.

fix: Verification of MS countersignatures now takes into account signer info digest and verifies it against digest of content info (timestamp info)

---

.github/workflows/tests.yaml

Originally brought up in #93, I have modified the tests workflow to fail-fast on non-experimental builds. As Rust's nightly channel is experimental, I have marked it as such.
Docs for following changes here: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures

ci: mark nightly as experimental in matrix

---

lib/src/modules/macho/parser.rs
lib/src/modules/macho/tests/testdata/chess.out

previously we were only parsing the parent level entitlement names requested, we now parse the array descendants as well if present. This sets us up to do entitlement hashing as well for detection opportunities.

feat: implement array entitlement parsing for complete entitlements on mach-o

---

site/content/docs/intro/yara_vs_yara-x.md

This is a fix for a minor typo in the doc
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

docs: fix minor typo

---

capi/include/yara_x.h
capi/src/compiler.rs
go/compiler.go
go/compiler_test.go
lib/src/compiler/errors.rs
lib/src/compiler/mod.rs
py/src/lib.rs
py/tests/test_api.py

Slow patterns are those that have atoms with less than 2 bytes. Such patterns can slow down scanning and the compiler raises a warning when it finds one of those patterns. The new APIs allow telling the compiler to raise an error instead of a warning.

feat: implement API for treating slow patterns as error instead of warnings

---

lib/src/compiler/tests/testdata/errors/69.out
parser/src/ast/mod.rs
parser/src/parser/cst2ast.rs
parser/src/parser/errors.rs
parser/src/parser/grammar.pest
parser/src/parser/tests/testdata/meta.yaml

This commit implements multiline string literals in metadata section.
```
rule a {
meta:
a = """
I'm a multiline string literal!
Hooray!
\"test\"
I also handle escapes, \x41\x42\x43!
... and emojis 🤖!
"""
condition:
true
}
```
While I'm here, also quote the metadata string values when printing the ast.

feat: Implement multiline string literals in metadata.

---

cli/src/commands/scan.rs
cli/src/help.rs

When using scan command you can now output in json or json-pretty format. The former is just a single JSON string per line while the latter is a pretty-printed JSON object.
Due to the output subsystem you can do things like:
./yr scan --output-format json rules/test.yara /bin | jq .path
and it will work, but you won't see the information about currently scanning files or the "final" message which tells you the number of files scanned. I'm guessing this is because the superscan is aware that stdout is being redirected somehow? Either way, this is a nice feature because it means we get the ability to pipe the JSON output to things like jq easily.

feat: add json output to scan command.

---

parser/Cargo.toml

To allow [Crates.io](https://crates.io/) , [lib.rs](https://lib.rs/) and the [Rust Digger](https://rust-digger.code-maven.com/) to link to it. See [the manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field) for the explanation.

chore: inherit `repository` field from workspace in `parser/Cargo.toml`

---

cli/src/commands/mod.rs
cli/src/commands/scan.rs

When running yr scan against some random files I have laying around I noticed a crash. I think it is because there is invalid (at least I think it is, I'm so bad at understanding unicode) unicode in the filename of one of the files contained in 84523ddad722e205e2d52eedfb682026928b63f919a7bf1ce6f1ad4180d0f507 (available on VT).
This changes it so the string is using the debug formatter which handles the invalid utf-8 better? This seems to work fine on my machine.

fix: Fix handling invalid(?) unicode in filenames.

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/scan.rs

This adds support for the `-m` flag to the scan command, which will print rule metadata.
I'm following the output of the original YARA implementation when outputting things as to try and not break any scripts that may expect the output in a certain format. I'm open to suggestions on ways to make this easier to read if you think we should just break existing scripts and come up with a new format here.

feat: Add support for rule metadata to be output in scan mode

---

cli/src/commands/scan.rs
lib/src/compiler/mod.rs
lib/src/compiler/rules.rs
lib/src/scanner/mod.rs

This commit adds a -g argument to the scan command which will print the tags of matching rules.
One thing I realized (and this is also true for metadata) is that if there is no tags we are still including them in the JSON (just as an empty list). When we print in text mode we have checks if the tags are empty and skipping them if so.
I'm open to changing the JSON output so that we do not include a "meta" and "tags" key if they are empty.

feat: Implement tag printing.

---

cli/src/commands/scan.rs

Add the -c option to output the number of rules that matched on each file. This is also implemented for the JSON output options.
I took this opportunity to refactor the code slightly to make the closure in the walker a little smaller by moving the logic on what to output and how into a separate function.

feat: Add -c options.

---

.github/workflows/code_health.yaml
.github/workflows/tests.yaml
lib/Cargo.toml
lib/build.rs
lib/src/modules/macho/parser.rs
lib/src/modules/pe/mod.rs
lib/src/modules/pe/parser.rs
lib/src/modules/protos/macho.proto
lib/src/modules/protos/pe.proto
lib/src/modules/protos/test_proto2.proto
lib/src/modules/protos/yaml.proto
lib/src/symbols/mod.rs
proto-yaml/src/yaml.proto

By default, .proto files are compiled using the pure-Rust compiler implemented by the `protobuf-rust`, but the `protoc` feature allows switching to `protoc`, the official Protobuf compiler. 
This required some changes in .proto files, because `protoc` is stricter than the pure-Rust protobuf compiler.

feat: add feature for compiling .proto files with `protoc`

---

lib/Cargo.toml
lib/src/scanner/mod.rs

This PR addresses issues raised in https://github.com/VirusTotal/yara-x/issues/182
In short, there are issue using `setns` syscall in projects embedding `yara-x` as a dependency.
The reason is that `setns` does not work if the current thread has parent or child thread with `CLONE_FS` flag.
The following has been done in this PR:
- allow library user to disable `wasmtime` parallelization **without** affecting default behavior.
- fix heartbeat thread so that it doesn't affect `setns` syscall of projects embedding `yara-x` and using `Scanner::set_timeout`

fix: setns related issues

---

lib/Cargo.toml
lib/src/modules/add_modules.rs
lib/src/modules/cuckoo/mod.rs
lib/src/modules/cuckoo/tests/mod.rs
lib/src/modules/cuckoo/tests/testdata/1.json
lib/src/modules/cuckoo/tests/testdata/1.out
lib/src/modules/cuckoo/tests/testdata/1.yar
lib/src/modules/cuckoo/tests/testdata/2.json
lib/src/modules/cuckoo/tests/testdata/2.out
lib/src/modules/cuckoo/tests/testdata/2.yar
lib/src/modules/modules.rs
lib/src/modules/protos/cuckoo.proto

The `cuckoo` module parses behaviour reports from the Cuckoo Sandbox https://cuckoosandbox.org/
The use of this module is currently discouraged. It is here for backward compatiblity with YARA, but it won't be actively mantained or improved as the Cuckoo Sandbox seems to be abandoned since 2017.

feat: implement `cuckoo` module.

---

cli/src/commands/compile.rs
cli/src/commands/mod.rs
cli/src/commands/scan.rs

The CLI was failing with an error telling that you can't use `--compiled-rules` with namespaces, even though no namespace was specified.

fix: bug while using `--compiled-rules` without namespaces.

---

lib/src/compiler/mod.rs
lib/src/compiler/rules.rs

With this change the `compile` command produces rules that can be used across different platforms. You can compile a set of rules in a Linux and use them in a Windows. Until now, the compiled rules were platform-specific, and could be used only in the same platform where it was compiled.

feat: serialize compiled rules in a platform-independent way.

---

cli/Cargo.toml
cli/src/commands/check.rs
cli/src/commands/fix.rs
cli/src/commands/scan.rs
cli/src/walk.rs

added the `json` variant to the existing `--output-format` arg, including the integration with the `--print-meta`, `--print-strings`, `--print-tags`, `--count`, `--tag` args
refactored the `ndjson` output implementation to match the `json` style
refactored the existing code to use DI (via dynamic dispatch) to separate the output logic from the rest

feat: json output

---

lib/src/modules/macho/mod.rs

Following up on a comment here: https://github.com/VirusTotal/yara-x/pull/248#discussion_r1850935651, which suggests only allocating the `md5_hash` object after passing initial validations for the given mach-o fields.

refactor: allocate md5 object only after validation of mach-o fields

---

lib/src/modules/cuckoo/mod.rs
lib/src/modules/cuckoo/schema.rs

updated the cuckoo module, as discussed in the past
changes:
1. the module now uses a `serde` schema to parse the input data into a struct. this improves the ergonomics of working with the data in the `#[module_export]` functions
2. the `#[module_export functions]` now return `Option<T>` rather than `T`. this is useful for when an error occurs (e.g. the input data is invalid) and there is no meaningful value to return otherwise

feat(cuckoo-update): data processed via serde schema, module_export fns return option

---

.github/workflows/release.yaml

The creation of Python packages started failing with the following error:
```
yara_x.pypy38-pp73-darwin.so has a minimum target of 10.12
Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=10.12' to update minimum supported macOS for this wheel.
```

ci: use specific OS versions while building Python extensions

---

lib/src/compiler/mod.rs
lib/src/compiler/tests/testdata/warnings/35.in
lib/src/compiler/tests/testdata/warnings/35.out
lib/src/compiler/tests/testdata/warnings/no_warnings.in

Regular expressions like `/[A-Za-z]/{N,}` with N>=2, can be very slow because they produce a large number of 2-bytes atoms. Raise warnings on those cases.

feat: raise warning with some patterns that have many 2-byte atoms.

---

.github/workflows/release.yaml

The gunzip utility doesn't like .gzip as a file extension and complains about extracting it.  Changing the filename to .gz resolves this and enabled tab completion on most Linux (and probably other) systems.

chore: change release file extensioin from .gzip to .gz

---

site/content/blog/leveraging-macho-module/index.md

Adding a blog post to document common uses for the `macho` module and features users can leverage for detections and rules.

docs: add blog post detailing some usage of macho module

---

site/content/docs/modules/macho.md

When reviewing the docs, noticed a few arrays for some of the things parsed were missing:
- imports
- linker_options

docs: add imports, exports, linker_options vectors to mach-o docs

---

.gitignore
Cargo.lock
fmt/src/lib.rs
py/Cargo.toml
py/pyproject.toml
py/src/lib.rs
py/tests/test_api.py
py/yara_x.pyi

- exposed the `format` API via the Python lib
- updated the typing stub
- documented the functions in Py
- added `__pycache__` to be ignored
- test for python formatting

feat: implement the Formatter API for python lib

---

cli/src/commands/scan.rs

This PR contains changes in the json output format of the scan command (`--output-format=json`), as (mostly) discussed in the <https://github.com/VirusTotal/yara-x/pull/239> PR.
The meta field is now an object, rather than an array of arrays.
Old format:
```json
"meta": [
[
"meta_1",
"value_1"
]
]
```
New format:
```json
"meta": {
"meta_1": "value_1"
}
```
This maps more appropriately to the idea of the meta fields being a key-value collection.
The top-level json is now formed from an object that then holds the hits as one of its fields, rather than the top-level json being an array of hits.
Old format:
```json
[
{
// hit object
}
]
```
New format:
```json
{
// some extra fields
"hits": [
{
// hit object
}
]
}
```
The benefit of the new representation is that it allows us to include extra …

refactor: json output vol2

---

lib/src/modules/macho/parser.rs

Found a few instances that need to be using `.saturating_add` for safer addition of the offsets parsed from the file or with struct sizes
Unlikely the binary blob is big enough to encounter the overflow, but better safe than sorry 😄

refactor: safer addition for offsets within superblobs

---

cli/src/tests/mod.rs
cli/src/walk.rs

One of the things I often run is "yr scan -r rules.yara ." when I have a collection of samples and I want to scan all of them in the current directory.
With the fix in #280 the path was being stripped to an empty string which would result in an error when trying to scan. Fix it by only performing the strip if the path is not equal to ".".

fix: don't strip prefix if path is exactly "."

---

parser/src/cst/mod.rs

I apparently don't understand enough about rust to know why it is running test code from comments, but it apparently is.

test: fix "cargo test" after cst change.

---

lib/src/scanner/mod.rs
lib/src/wasm/mod.rs

Each WASM module tries to reserve a large amount of virtual address space (4GB in 64-bits systems). This doesn't means that they actually needs this amount of RAM, it only means that it reserves address space in case the memory required by the module grows dynamically. As each YARA-X scanner needs one of these WASM modules, this implies that YARA-X ends up reserving a very large amount of virtual address space. This is problematic in some environments where the amount of virtual address space per process is limited (in Docker containers, for instance). 
This PR reduces the amount of virtual address space reserved by each WASM module, mainly by limiting the amount of memory of each WASM module to 16MB. This is enough to accommodate very large sets of rules, with millions of rules and …

fix: reduce consumption of virtual address space.

---

py/tests/test_api.py

With the API changes to the linter we currently do not have a good way to expose this in the python API, so remove these failing tests for now.

fix: Remove broken tests.

---

docs/YARA-X Config Guide.md

d3c4750c3e7865e72a1bab173dbc0f8972bb28dc changed config file handling so that unknown fields now cause parsing errors instead of being silently ignored. Fix the docs to reflect this change.

fix: Fix docs after change to unknown config entries.

---

.github/workflows/code_health.yaml
.github/workflows/tests.yaml
Cargo.lock
Cargo.toml
lib/fuzz/Cargo.lock
lib/src/compiler/ir/tests/mod.rs

wasmtime 30.0.0 adds support for 32 bits platforms by using the `pulley` WASM interpreter instead of generating native code using `cranelift`.

chore: upgrade `wasmtime` to version 30.0.0.

---

.github/workflows/code_health.yaml
.github/workflows/coverage.yaml
.github/workflows/golang.yaml
.github/workflows/pr_title.yaml
.github/workflows/python.yaml
.github/workflows/release.yaml
.github/workflows/site.yaml
.github/workflows/tests.yaml

**Summary**
This PR updates GitHub Actions to their latest versions and pins them to specific SHA hashes rather than version tags to mitigate supply chain attack risks.
**Security Rationale**
Using version tags like `@v4` creates a security vulnerability as the content behind those tags can be modified at any time by action maintainers or by attackers who compromise their accounts. Recent supply chain attacks like the xz vulnerability (CVE-2024-3094) demonstrate how dependencies can be compromised through trusted distribution mechanisms.
By pinning to immutable SHA hashes, we ensure that the exact code run by our workflows is never silently changed.
**Changes**
This PR updates multiple GitHub Actions to their latest versions, including:
- actions/checkout from v4 to v4.2.2 …

chore: Pin GitHub Actions to immutable SHA hashes

---

lib/src/modules/elf/mod.rs
lib/src/modules/macho/mod.rs
lib/src/modules/pe/mod.rs

There are a bunch of functions in the `elf`, `pe`, and `macho` modules who's results can be memoized (imphash, import_md5, etc).
This can result in a significant performance boost in cases where a large number of calls to these functions are made (usually because a large number of rules are used in a single scanner).
This is very similar to what is done in the hash module.
I'm not very experienced with rust so apologies if I've missed anything obvious.
A simple example to demonstrate the benefits is to run the following rule on any sort of `pe` file:
```yar
rule memoize_example {
import "pe"
condition:
pe.calculate_checksum() == 0 or 
pe.calculate_checksum() == 1 or 
pe.calculate_checksum() == 2 or 
pe.calculate_checksum() == 3 or 
...
pe.calculate_checksum() == 100
}
```
This is …

perf: memoized some module functions

---

site/config/_default/markup.toml

Goldmark's Typographer by default substitutes `--` with `&ndash`.
This commit disables the default substitution ensuring command line arguments remain accurate. As such, titles on [YARA-X's CLI Commands docs](https://virustotal.github.io/yara-x/docs/cli/commands/) would become accurate again (e.g., `–profiling` needs to be `--profiling`).

docs: Disable Goldmark's Typographer `--` substitution

---

lib/src/compiler/emit.rs
lib/src/compiler/ir/ast2ir.rs
lib/src/compiler/ir/mod.rs
lib/src/compiler/ir/tests/mod.rs
lib/src/compiler/ir/tests/testdata/3.cse.ir
lib/src/compiler/ir/tests/testdata/3.hoisting.ir
lib/src/compiler/ir/tests/testdata/3.ir
lib/src/compiler/ir/tests/testdata/3.no-folding.ir
lib/src/compiler/tests/testdata/warnings/37.in
lib/src/compiler/tests/testdata/warnings/37.out
lib/src/compiler/warnings.rs
lib/src/modules/elf/mod.rs
lib/src/modules/hash/mod.rs
lib/src/modules/mod.rs
lib/src/symbols/mod.rs
lib/src/types/array.rs
lib/src/types/func.rs
lib/src/types/mod.rs
lib/src/types/structure.rs
lib/src/variables.rs
lib/src/wasm/mod.rs
lib/src/wasm/string.rs
macros/src/wasm_export.rs
parser/src/ast/cst2ast.rs
parser/src/ast/mod.rs
test.yar

Now a `TypeValue` can have additional constraints that gives the compiler information about the values. For instance, a `TypeValue` of type string can have a constraint that specifies that the value is always lowercase. These constraints allow to raise warnings in situations where a condition can't be met, like comparing a lowercase string with some other string that contains uppercase characters.

feat: implement constraints for TypeValue

---

lib/src/compiler/emit.rs
lib/src/compiler/ir/ast2ir.rs
lib/src/compiler/ir/mod.rs
lib/src/compiler/ir/tests/testdata/3.cse.ir
lib/src/compiler/ir/tests/testdata/3.hoisting.ir
lib/src/compiler/ir/tests/testdata/3.ir
lib/src/compiler/ir/tests/testdata/3.no-folding.ir
lib/src/compiler/ir/tests/testdata/4.cse.ir
lib/src/compiler/ir/tests/testdata/4.hoisting.ir
lib/src/compiler/ir/tests/testdata/4.ir
lib/src/compiler/ir/tests/testdata/4.no-folding.ir
lib/src/compiler/ir/tests/testdata/6.cse.ir
lib/src/compiler/ir/tests/testdata/6.hoisting.ir
lib/src/compiler/ir/tests/testdata/6.ir
lib/src/compiler/ir/tests/testdata/6.no-folding.ir
lib/src/compiler/ir/tests/testdata/7.cse.ir
lib/src/compiler/ir/tests/testdata/7.hoisting.ir
lib/src/compiler/ir/tests/testdata/7.ir
lib/src/compiler/ir/tests/testdata/7.no-folding.ir
lib/src/tests/mod.rs
lib/src/types/array.rs
lib/src/types/func.rs
lib/src/types/map.rs
lib/src/types/mod.rs
lib/src/wasm/mod.rs
macros/src/wasm_export.rs
test.yar

With this change every array and map now has a built-in method `len()` which returns the number of items in the array or map.

feat: implement `len` method for arrays and maps.

---

lib/src/modules/cuckoo/mod.rs
lib/src/modules/cuckoo/schema.rs

I noticed that in the original yara the scheme of cuckoo JSON report is less strict. For example report does not have to contain `network` attribute. In contrast with this behavior yara-x enforces a presence of some attributes, otherwise it does not match a sample, because of parsing error in serde.
Therefore I relaxed cuckoo JSON scheme to do not enforce a presence of any attributes (all of them are optional now).

fix: Less strict scheme of cuckoo report

---

lib/src/compiler/ir/tests/testdata/1.cse.ir
lib/src/compiler/ir/tests/testdata/1.hoisting.ir
lib/src/compiler/ir/tests/testdata/1.ir
lib/src/compiler/ir/tests/testdata/1.no-folding.ir
lib/src/compiler/tests/testdata/warnings/40.in
lib/src/compiler/tests/testdata/warnings/40.out
parser/src/ast/cst2ast.rs
parser/src/parser/tests/testdata/arithmetic-ops.ast
parser/src/parser/tests/testdata/arithmetic-ops.cst
parser/src/parser/tests/testdata/arithmetic-ops.in
parser/src/parser/tests/testdata/expr-1.ast

Optimizes the handling of unary minus operators in the parser by merging a minus sign immediately followed by a positive literal integer into a single literal with a negative value. This prevents the creation of unnecessary intermediate `Expr::Minus` nodes and simplifies the AST.

refactor: improve unary minus handling in the parser.

---

cli/src/help.rs
site/content/docs/cli/commands.md

The docs and help `yr  scan --help` had a small typo for disabling the `slow_pattern` warning. Small change to fix the documentation.
```sh
kmsec@penguin:~$ yr scan b64.yara b64.js --disable-warnings=slow_patterns
error: `slow_patterns` is not a valid warning code
```

docs: `slow_pattern` typo in doc and help

---

lib/src/wasm/mod.rs
site/content/docs/writing_rules/conditions.md

Port of https://github.com/VirusTotal/yara/pull/2153 to Yara-X
Parse IEEE 754 float and double formats from any offset and to create signatures based on the interpreted floating point value.
Sample rule:
```
rule ieee754_test {
condition:
float32(0) == 1.0 and 
float32be(4) == 1.0 and
float32(8) > 0.74 and
float32be(12) < 0.76 and
float64(16) == 1.0 and
float64be(24) == 1.0 and
float64be(32) == 0.01171875
}
```
Sample file:
```
00000000: 0000 803f 3f80 0000  ...??...
00000008: 0000 403f 3f40 0000  ..@??@..
00000010: 0000 0000 0000 f03f  .......?
00000018: 3ff0 0000 0000 0000  ?.......
00000020: 3f88 0000 0000 0000  ?.......
```

feat: add support for parsing IEEE754 float/double 

---

lib/src/modules/console.rs
site/content/docs/modules/console.md

Add support for handling boolean arguments in console.log, so you can now do things like "console.log(pe.is_32bit())" since that returns a boolean in YARA-X but an integer in original YARA.

feat: Support boolean in console.log()

---

lib/fuzz/Cargo.lock

I was fuzzing locally and realized there we were a few releases behind on `libfuzzer-sys`. 
Updated the dependencies in the `lib/fuzz` directory.

chore: update fuzzer dependencies

---

.github/workflows/tests.yaml
Cargo.lock
cli/Cargo.toml
cli/src/commands/check.rs
cli/src/config.rs
cli/src/tests/check.rs
cli/src/tests/scan.rs
cli/src/tests/testdata/foo.yar
lib/src/compiler/linters.rs
site/content/docs/cli/config.md

The config file now accepts the following:
```
[check.metadata]
my_meta = { type = "string", regexp = "(foo|bar)" }
```
In this case the metadata `my_meta` must be of type string and match the regexp `(foo|bar)`.

feat: implement regexp validation for metadata

---

.github/workflows/pr_title.yaml

`aslafy-z/conventional-pr-title-action` has been deprecated: https://github.com/aslafy-z/conventional-pr-title-action?tab=readme-ov-file#important-notice-this-repository-has-been-archived
Using the recommended replacement https://github.com/amannn/action-semantic-pull-request

ci: replace deprecated GitHub Action

---

parser/src/cst/mod.rs

Add implementation of `token_at_offset` method for CST `Node` along with `TokenAtOffset` return type.
This method can be used in language server development.

feat: implement `token_at_offset` method for `Node`.

---

cli/src/commands/scan.rs
cli/src/help.rs
py/src/lib.rs
py/tests/test_api.py
py/yara_x.pyi
site/content/docs/api/python.md
site/content/docs/cli/commands.md

New parameter in CLI tested locally.
New parameter in Python code not tested, as I didn't find any usage of `test_api.py`, so I just compiled **yara-x-py**.

feat: support of "max-matches-per-pattern" parameter in CLI and Python API

---

capi/src/lib.rs

It seems like unless `#[no_mangle]` is specified, the symbol is not exported (or is exported absolutely mangled, that I wasn't even able to locate it in the list of exported symbols).

fix(capi): export and do not mangle yrx_finalize
